"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabase";
import toast, { Toaster } from "react-hot-toast";
import Link from "next/link";

type CrosshairDetail = {
  id: number;
  name: string;
  slug: string;
  code: string;
  image: string | null;
  likes: number;
  copies: number;
  views: number;
  player: string | null;
  team: string | null;
  resolution?: string;
  dpi?: number;
  sensitivity?: number;
  monitor_hz?: number;
  mouse_model?: string;
};

type Comment = {
  id: number;
  username: string;
  comment: string;
  rating: number;
  created_at: string;
};

export default function CrosshairDetailPage() {
  const params = useParams();
  const slug = params?.slug as string;

  const [crosshair, setCrosshair] = useState<CrosshairDetail | null>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [loading, setLoading] = useState(true);

  // Form State
  const [newUsername, setNewUsername] = useState("");
  const [newComment, setNewComment] = useState("");
  const [newRating, setNewRating] = useState(5);

  useEffect(() => {
    if (slug) {
      loadData();
    }
  }, [slug]);

  async function loadData() {
    setLoading(true);

    // Crosshair Bilgisini Getir
    const { data: item, error } = await supabase
      .from("approved_crosshairs")
      .select("*")
      .eq("slug", slug)
      .single();

    if (error || !item) {
      setLoading(false);
      return;
    }

    setCrosshair(item);

    // Görüntülenme Sayısını Artır
    await supabase
      .from("approved_crosshairs")
      .update({ views: (item.views || 0) + 1 })
      .eq("id", item.id);

    // Yorumları Getir
    const { data: commentData } = await supabase
      .from("crosshair_comments")
      .select("*")
      .eq("crosshair_id", item.id)
      .order("created_at", { ascending: false });

    if (commentData) {
      setComments(commentData);
    }

    setLoading(false);
  }

  // CFG Dosyası Oluşturup İndir
  const downloadCFG = () => {
    if (!crosshair) return;

    const cfgContent = `// CS2 Crosshair Config - ${crosshair.name}\n// Generated by CS2 Crosshair Hub\n\napply_crosshair_code "${crosshair.code}"\n`;
    const blob = new Blob([cfgContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${crosshair.slug}_crosshair.cfg`;
    link.click();
    URL.revokeObjectURL(url);

    toast.success(".cfg dosyası indirildi!");
  };

  // Yorum Gönder
  const handleCommentSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!crosshair || !newUsername.trim() || !newComment.trim()) {
      toast.error("Lütfen tüm alanları doldurun.");
      return;
    }

    const { error } = await supabase.from("crosshair_comments").insert({
      crosshair_id: crosshair.id,
      username: newUsername,
      comment: newComment,
      rating: newRating,
    });

    if (error) {
      toast.error("Yorum eklenirken hata oluştu!");
    } else {
      toast.success("Yorumun başarıyla gönderildi ⭐");
      setNewComment("");
      setNewUsername("");
      loadData(); // Yenile
    }
  };

  const copyCode = () => {
    if (!crosshair) return;
    navigator.clipboard.writeText(crosshair.code);
    toast.success("Crosshair kodu panoya kopyalandı!");
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <p className="text-xl text-zinc-400 animate-pulse">Yükleniyor...</p>
      </div>
    );
  }

  if (!crosshair) {
    return (
      <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center gap-4">
        <h1 className="text-3xl font-bold">Crosshair Bulunamadı 😞</h1>
        <Link href="/" className="text-red-500 underline">
          Ana Sayfaya Dön
        </Link>
      </div>
    );
  }

  return (
    <>
      <Toaster position="top-center" />
      <main className="min-h-screen bg-black text-white py-12 px-6">
        <div className="max-w-5xl mx-auto">
          {/* Geri Dön Butonu */}
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-zinc-400 hover:text-white mb-8 transition"
          >
            ← Ana Sayfaya Dön
          </Link>

          {/* Üst Başlık Kartı */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-3xl p-8 mb-10 flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="w-full md:w-1/2 flex flex-col items-center justify-center bg-black border border-zinc-800 rounded-2xl p-6">
              <img
                src={
                  crosshair.image
                    ? `/crosshairs/${crosshair.image}`
                    : "/crosshairs/default.png"
                }
                alt={crosshair.name}
                className="max-h-56 object-contain"
              />
            </div>

            <div className="w-full md:w-1/2 flex flex-col gap-4">
              <span className="text-xs bg-red-600/20 text-red-400 border border-red-500/30 px-3 py-1 rounded-full w-max font-semibold">
                {crosshair.team || "Topluluk"}
              </span>
              <h1 className="text-4xl font-black">{crosshair.name}</h1>
              <p className="text-zinc-400">
                Oyuncu: <strong className="text-white">{crosshair.player || crosshair.name}</strong>
              </p>

              <div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 font-mono text-xs overflow-hidden text-ellipsis">
                {crosshair.code}
              </div>

              <div className="flex gap-3 mt-2">
                <button
                  onClick={copyCode}
                  className="flex-1 bg-red-600 hover:bg-red-700 py-3 rounded-xl font-semibold transition text-sm"
                >
                  📋 Kodu Kopyala
                </button>
                <button
                  onClick={downloadCFG}
                  className="bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 px-4 py-3 rounded-xl font-semibold transition text-sm"
                >
                  📥 .CFG İndir
                </button>
              </div>
            </div>
          </div>

          {/* OYUNCU & DONANIM AYARLARI */}
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            🎮 Oyuncu & Sistem Ayarları
          </h2>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4 mb-12">
            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-center">
              <p className="text-xs text-zinc-500 mb-1">📐 Çözünürlük</p>
              <p className="font-bold text-sm text-white">
                {crosshair.resolution || "1280x960"}
              </p>
            </div>

            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-center">
              <p className="text-xs text-zinc-500 mb-1">🖱️ DPI</p>
              <p className="font-bold text-sm text-white">
                {crosshair.dpi || 800}
              </p>
            </div>

            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-center">
              <p className="text-xs text-zinc-500 mb-1">🎯 Duyarlılık (Sens)</p>
              <p className="font-bold text-sm text-white">
                {crosshair.sensitivity || 1.2}
              </p>
            </div>

            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-center">
              <p className="text-xs text-zinc-500 mb-1">🖥️ Monitör</p>
              <p className="font-bold text-sm text-white">
                {crosshair.monitor_hz ? `${crosshair.monitor_hz} Hz` : "240 Hz"}
              </p>
            </div>

            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-center col-span-2 sm:col-span-1">
              <p className="text-xs text-zinc-500 mb-1">🐭 Fare</p>
              <p className="font-bold text-xs text-white truncate">
                {crosshair.mouse_model || "Logitech GPX"}
              </p>
            </div>
          </div>

          {/* YORUMLAR VE DEĞERLENDİRME */}
          <div className="grid md:grid-cols-2 gap-8">
            {/* Yorum Ekleme Formu */}
            <div className="bg-zinc-900 border border-zinc-800 rounded-3xl p-6">
              <h3 className="text-xl font-bold mb-4">✍️ Yorum Yap & Puan Ver</h3>
              <form onSubmit={handleCommentSubmit} className="flex flex-col gap-4">
                <div>
                  <label className="text-xs text-zinc-400 block mb-1">Kullanıcı Adın</label>
                  <input
                    type="text"
                    value={newUsername}
                    onChange={(e) => setNewUsername(e.target.value)}
                    placeholder="Örn: s1mple_fan"
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-sm outline-none focus:border-red-500 transition"
                  />
                </div>

                <div>
                  <label className="text-xs text-zinc-400 block mb-1">Puanın</label>
                  <select
                    value={newRating}
                    onChange={(e) => setNewRating(Number(e.target.value))}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-sm outline-none focus:border-red-500 transition"
                  >
                    <option value={5}>⭐⭐⭐⭐⭐ (5/5) - Mükemmel</option>
                    <option value={4}>⭐⭐⭐⭐ (4/5) - Çok İyi</option>
                    <option value={3}>⭐⭐⭐ (3/5) - Ortalama</option>
                    <option value={2}>⭐⭐ (2/5) - Kötü</option>
                    <option value={1}>⭐ (1/5) - Berbat</option>
                  </select>
                </div>

                <div>
                  <label className="text-xs text-zinc-400 block mb-1">Yorumun</label>
                  <textarea
                    rows={3}
                    value={newComment}
                    onChange={(e) => setNewComment(e.target.value)}
                    placeholder="Bu nişangah hakkındaki düşüncelerin..."
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-sm outline-none focus:border-red-500 transition resize-none"
                  />
                </div>

                <button
                  type="submit"
                  className="bg-red-600 hover:bg-red-700 py-3 rounded-xl font-semibold transition text-sm"
                >
                  Yorum Gönder
                </button>
              </form>
            </div>

            {/* Yorum Listesi */}
            <div className="bg-zinc-900 border border-zinc-800 rounded-3xl p-6 flex flex-col gap-4">
              <h3 className="text-xl font-bold mb-2">
                💬 Yorumlar ({comments.length})
              </h3>

              {comments.length === 0 ? (
                <p className="text-zinc-500 text-sm">
                  Henüz yorum yapılmamış. İlk yorumu sen yap!
                </p>
              ) : (
                <div className="flex flex-col gap-3 max-h-96 overflow-y-auto pr-2">
                  {comments.map((c) => (
                    <div
                      key={c.id}
                      className="bg-zinc-950 border border-zinc-800 rounded-xl p-4"
                    >
                      <div className="flex justify-between items-center mb-1">
                        <span className="font-bold text-sm text-white">
                          {c.username}
                        </span>
                        <span className="text-yellow-500 text-xs">
                          {"⭐".repeat(c.rating)}
                        </span>
                      </div>
                      <p className="text-zinc-300 text-sm">{c.comment}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}